### PR TITLE
Validate images build without pushing on PR

### PR DESCRIPTION
**Pull request by cedric-anne**
With this proposal, images build would be done when a PR is opened, in order to be able to validate that proposed changes are not breaking images build.

Workflow would also be trigerred when corresponding workflow configuration file would be changed.

### CODE REVIEW

**Comment by jdecool** [comment]
Hi @cedric-anne ,

Thanks for this PR.

It seems that the CI run without the correct credentials.
I need to investigate about how we can fix that.

**Comment by cedric-anne** [comment]
Indeed, I had to put my credentials on my own fork.

Proposed configuration would work when PR is opened from the same repository, but not from a fork that has no credentials configured.

see https://github.com/cedric-anne/php/actions/runs/2021365693

**Comment by cedric-anne** [comment]
> It seems that the CI run without the correct credentials.
> I need to investigate about how we can fix that.

It seems that the solution is to not login on Docker Hub from PR.

I get this solution from https://github.com/phparkitect/arkitect/blob/main/.github/workflows/build.yml

**Comment by cedric-anne** [comment]
Official PHP images on alpine 3.12 were removed 9 months ago (see https://github.com/docker-library/php/pull/1166 where 3.12 were replaced by 3.14) and images on alpine 3.13 were removed 4 months ago ( see https://github.com/docker-library/php/pull/1226  where 3.13 were replaced by 3.15).

Removing support of these old alpine versions would highly reduce the build count.

**Review by jdecool — APPROVED** [review]

**Comment by jdecool** [comment]
Awesome !

Thanks @cedric-anne.

> Removing support of these old alpine versions would highly reduce the build count.

Yes, I need to clean some images.

**Pull request merged**
