### PR TITLE
Add Alpine 3.15 images

### PR DESCRIPTION
**Pull request by cedric-anne**
PHP official images are available on alpine 3.15.

I propose to add phpdaily images on alpine 3.15 too.

### CODE REVIEW

**Comment by jdecool** [comment]
Thanks.

I really appreciate this PR.
I'll make some tests tomorrow on this image.

**Comment by cedric-anne** [comment]
For information, I just copied alpine3.14 directories and replace `FROM alpine:3.14` by `FROM alpine:3.15`.

**Comment by cedric-anne** [comment]
I rebased to validate build.

**Comment by jdecool** [comment]
Thanks @cedric-anne

**Pull request merged**
